// Code generated by "go generate". Please don't change this file directly.

package verifiedpermissions

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// IdentitySource_OpenIdConnectIdentityTokenConfiguration AWS CloudFormation Resource (AWS::VerifiedPermissions::IdentitySource.OpenIdConnectIdentityTokenConfiguration)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-verifiedpermissions-identitysource-openidconnectidentitytokenconfiguration.html
type IdentitySource_OpenIdConnectIdentityTokenConfiguration struct {

	// ClientIds AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-verifiedpermissions-identitysource-openidconnectidentitytokenconfiguration.html#cfn-verifiedpermissions-identitysource-openidconnectidentitytokenconfiguration-clientids
	ClientIds []string `json:"ClientIds,omitempty"`

	// PrincipalIdClaim AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-verifiedpermissions-identitysource-openidconnectidentitytokenconfiguration.html#cfn-verifiedpermissions-identitysource-openidconnectidentitytokenconfiguration-principalidclaim
	PrincipalIdClaim *string `json:"PrincipalIdClaim,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *IdentitySource_OpenIdConnectIdentityTokenConfiguration) AWSCloudFormationType() string {
	return "AWS::VerifiedPermissions::IdentitySource.OpenIdConnectIdentityTokenConfiguration"
}
