// Code generated by "go generate". Please don't change this file directly.

package verifiedpermissions

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// IdentitySource_OpenIdConnectTokenSelection AWS CloudFormation Resource (AWS::VerifiedPermissions::IdentitySource.OpenIdConnectTokenSelection)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-verifiedpermissions-identitysource-openidconnecttokenselection.html
type IdentitySource_OpenIdConnectTokenSelection struct {

	// AccessTokenOnly AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-verifiedpermissions-identitysource-openidconnecttokenselection.html#cfn-verifiedpermissions-identitysource-openidconnecttokenselection-accesstokenonly
	AccessTokenOnly *IdentitySource_OpenIdConnectAccessTokenConfiguration `json:"AccessTokenOnly,omitempty"`

	// IdentityTokenOnly AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-verifiedpermissions-identitysource-openidconnecttokenselection.html#cfn-verifiedpermissions-identitysource-openidconnecttokenselection-identitytokenonly
	IdentityTokenOnly *IdentitySource_OpenIdConnectIdentityTokenConfiguration `json:"IdentityTokenOnly,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *IdentitySource_OpenIdConnectTokenSelection) AWSCloudFormationType() string {
	return "AWS::VerifiedPermissions::IdentitySource.OpenIdConnectTokenSelection"
}
